name: strongR-frida-build

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:

jobs: 
  check_version:
    runs-on: ubuntu-20.04

    outputs:
      FRIDA_VERSION: ${{ steps.pullFridaLatestRelease.outputs.FRIDA_VERSION }}
      ALREADY_RELEASE: ${{ steps.checkReleaseVersion.outputs.ALREADY_RELEASE }}
    steps:
      - name: Pull Frida Latest Release
        id: pullFridaLatestRelease
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const releaseResponse = await github.rest.repos.getLatestRelease({
              owner: 'frida',
              repo: 'frida',
            })
            const {
              data: { tag_name: ver }
            } = releaseResponse;
            core.setOutput('FRIDA_VERSION', ver);
      - name: Check release version
        id: checkReleaseVersion
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              const releaseVersion = '${{ steps.pullFridaLatestRelease.outputs.FRIDA_VERSION }}'
              const releaseResponse = await github.rest.repos.getReleaseByTag({
                owner: '${{ secrets.GIT_OWNER }}',
                repo: '${{ secrets.GIT_REPO }}',
                tag: releaseVersion
              });
              const {
                data: { tag_name: ver }
              } = releaseResponse;
              if (ver == '${{ steps.pullFridaLatestRelease.outputs.FRIDA_VERSION }}'){
                  core.setOutput('ALREADY_RELEASE', '1');
              }
              else{
                  core.setOutput('ALREADY_RELEASE', '0');
              }
            } catch (e) {
              if(e.message == 'Not Found'){
                core.setOutput('ALREADY_RELEASE', '0');
              }
              else{
                core.setFailed(e.message);
              }
            }

  android_build:
    runs-on: ubuntu-20.04
    needs: [check_version]
    if: needs.check_version.outputs.ALREADY_RELEASE == '0'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r25b

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison xz-utils ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 -y
          sudo gem install fpm -v 1.11.0 --no-document
          python3 -m pip install lief
          python3 -m pip install graphlib

      - name: build frida for Android
        shell: bash
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git clone ${{ secrets.PATCH_REPO }} Patchs
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          git clone -b ${{ needs.check_version.outputs.FRIDA_VERSION }} --recurse-submodules https://github.com/frida/frida
          cd frida/subprojects/frida-core
          git am ../../../Patchs/strongR-frida/frida-core/*.patch
      - name: two step patch   
        shell: bash
        run: |
          cd frida/subprojects/frida-gum/gum
          git am ../../../../Patchs/strongR-frida/frida-gum/*.patch
          cd ../../../
          ./configure --host=android-arm
          make core-android-arm
          ./configure --host=android-arm64
          make core-android-arm64
          ./configure --host=android-x86
          make core-android-x86
          ./configure --host=android-x86_64
          make core-android-x86_64
      - name: package build result for Android
        shell: bash
        run: |
          pushd frida

          mkdir release-assets

          xz -c build/frida-android-arm/bin/frida-server > release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
          xz -c build/frida-android-arm64/bin/frida-server > release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
          xz -c build/frida-android-x86/bin/frida-server > release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
          xz -c build/frida-android-x86_64/bin/frida-server > release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
          xz -c build/frida-android-arm/bin/frida-inject > release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
          xz -c build/frida-android-arm64/bin/frida-inject > release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
          xz -c build/frida-android-x86/bin/frida-inject > release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
          xz -c build/frida-android-x86_64/bin/frida-inject > release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
          xz -c build/frida-android-arm/lib/frida/32/frida-gadget.so > release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.so.xz
          xz -c build/frida-android-arm64/lib/frida/64/frida-gadget.so > release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.so.xz
          xz -c build/frida-android-x86/lib/frida/32/frida-gadget.so > release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.so.xz
          xz -c build/frida-android-x86_64/lib/frida/64/frida-gadget.so > release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.so.xz

          popd
      - name: Upload artifact hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm
          path: frida/release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
      - name: Upload artifact hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64
          path: frida/release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
      - name: Upload artifact hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86
          path: frida/release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
      - name: Upload artifact hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64
          path: frida/release-assets/hluda-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
      - name: Upload artifact hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm
          path: frida/release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.xz
      - name: Upload artifact hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64
          path: frida/release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.xz
      - name: Upload artifact hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86
          path: frida/release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.xz
      - name: Upload artifact hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64
          path: frida/release-assets/hluda-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.xz
      - name: Upload artifact hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.so.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.so
          path: frida/release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.so.xz
      - name: Upload artifact hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.so.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.so
          path: frida/release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.so.xz
      - name: Upload artifact hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.so.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.so
          path: frida/release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.so.xz
      - name: Upload artifact hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.so.xz
        uses: actions/upload-artifact@v4
        with:
          name: hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.so
          path: frida/release-assets/hluda-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.so.xz


  create_release:
    runs-on: ubuntu-20.04
    needs: [check_version, android_build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true
      - name: Ddisplay release assets
        run: tree ${{ github.workspace }}/release-assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check_version.outputs.FRIDA_VERSION }}
          fail_on_unmatched_files: true
          files: release-assets/*
